### ISSUE TITLE
Where are recent files displayed?

### ISSUE THREAD

**Issue by lambdamusic** [NERSC/jupyterlab-recents#2]
I've installed the extension but can't see anything in the UI.

**Comment by ecolbinado** [comment]
Can't figure it out either!

**Comment by moble** [comment]
After refreshing the jupyterlab window, I see it (and [the favorites menu](https://github.com/tslaton/jupyterlab-favorites)) under the File menu:

<img width="273" alt="ScreenShot" src="https://user-images.githubusercontent.com/1470769/73488693-62718f00-4377-11ea-8fdd-c3d69c45246e.png">

**Comment by ecolbinado** [comment]
> After refreshing the jupyterlab window, I see it (and [the favorites menu](https://github.com/tslaton/jupyterlab-favorites)) under the File menu:
> 
> <img alt="ScreenShot" width="273" src="https://user-images.githubusercontent.com/1470769/73488693-62718f00-4377-11ea-8fdd-c3d69c45246e.png">

at last! :D
