### ISSUE TITLE
not support latest jupyterlab 2.1.2?

### ISSUE THREAD

**Issue by badiku** [NERSC/jupyterlab-recents#6]
tried to install it, but failed. 

some info:

`jupyter labextension install jupyterlab-recents`

>An error occured.
>ValueError: The extension "jupyterlab-recents" does not yet support the current version of JupyterLab.
>Conflicting Dependencies:
>JupyterLab              Extension      Package
> \>=2.1.2 <2.2.0          >=1.0.0 <2.0.0 @jupyterlab/application
> \>=4.1.0 <4.2.0          >=3.0.0 <4.0.0 @jupyterlab/coreutils
> \>=2.1.2 <2.2.0          >=1.0.0 <2.0.0 @jupyterlab/docmanager

on my Win10:
`jupyter labextension list`
> Known labextensions:
>    app dir: python-3.7.7.amd64\share\jupyter\lab
>         @aquirdturtle/collapsible_headings v2.2.0 enabled  ok
>         @bokeh/jupyter_bokeh v2.0.0 enabled  ok
>         @deck.gl/jupyter-widget v8.1.0 enabled  ok
>         @jupyter-voila/jupyterlab-preview v1.0.0 enabled  ok
>         @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
>         @jupyter-widgets/jupyterlab-sidecar v0.5.0 enabled  ok
>         @jupyterlab/toc v3.0.0 enabled  ok
>         @jupyterlab/vega3-extension v2.0.0 enabled  ok
>         @krassowski/jupyterlab_go_to_definition v1.0.0 enabled  ok
>         @lckr/jupyterlab_variableinspector v0.5.0 enabled  ok
>         @pyviz/jupyterlab_pyviz v0.9.0 enabled  ok
>         @ryantam626/jupyterlab_code_formatter v1.3.1 enabled  ok
>         bqplot v0.5.6 enabled  ok
>         jupyter-leaflet v0.12.3 enabled  ok
>         jupyter-matplotlib v0.7.2 enabled  ok
>         jupyterlab-spreadsheet v0.3.2 enabled  ok
>         list v2.0.19 enabled  ok
>         transient-display-data v0.4.0 enabled  ok

`pip list | findstr upyter`
> jupyter                       1.0.0
> jupyter-client                6.1.3
> jupyter-console               6.1.0
> jupyter-core                  4.6.3
> jupyter-server                0.1.1
> jupyter-sphinx                0.2.4
> jupyterlab                    2.1.2
> jupyterlab-code-formatter     1.3.1
> jupyterlab-launcher           0.13.1
> jupyterlab-pygments           0.1.1
> jupyterlab-server             1.1.4

**Comment by fcollonval** [comment]
@mlhenderson do you have time to publish this package now that the master is compatible with JLab 2?

Let me know if I can help.

**Comment by shreddd** [comment]
@fcollonval - is it just a matter of publishing to NPM ?

**Comment by fcollonval** [comment]
@shreddd yes as the version has been bumped. If you have written right on npm. You can publish the package with:

```sh
npm login
npm publish --access=public
```

**Comment by shreddd** [comment]
Hi @fcollonval - ok - update pushed to NPM. Please test and let us know if it works for you.

**Comment by fcollonval** [comment]
@shredd thanks a lot. I successfully installed and test the extension on
JupyterLab v2.

**Comment by badiku** [comment]
I thought this's jupyterlab-favorites, what a mistake

so , what's this extention for? not clear.
why not put something on readme?

what will happen if I install this? 

I tried to enable it , and disable it, did not find any difference.
totally confused

**Comment by mlhenderson** [comment]
I'm closing this issue because I think the v2 install is working, but let us know if something seems broken.  For reference, jupyterlab-recents records and provides links from the file menu for documents and folders recently used.  The jupyterlab-favorites extension allows users to favorite folders and documents and have them appear in the filebrowser interface in the left sidebar while navigating.  At NERSC, the favorites extension is used to keep user's home and scratch directories available from the filebrowser.
